// id: Int!
// nomenclature: String!
// nsn: String!
// partNumber: String!
// cageCode: String!
// unitOfIssue: String!
// unitPrice: String!
// isg: String!
// commodityCode: String!
// shelfLifeCode: S0!
// typeCargoCode: "z"// hazardousMaterialCode: String!
// rid: String!
// location: String!
// nmfc: S251g!
// wuc: String!
// description: String!
// manufacturer: String!
// qrCode: String!
// Orders: [Order]!

export const Part = [
  {
    nomenclature: 'engine assembly',
    nsn: '1234567890123',
    partNumber: 'eng123',
    cageCode: 'abc12',
    unitOfIssue: 'EA',
    unitPrice: '50,000.00',
    isg: '123',
    commodityCode: 'a123',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'fhz',
    location: '01ae10b010',
    nmfc: '251123',
    description: 'high-performance jet engine assembly',
    manufacturer: 'jet engines inc.',
  },
  {
    nomenclature: 'landing gear',
    nsn: '2345648901234',
    partNumber: 'lg456',
    cageCode: 'def34',
    unitOfIssue: 'EA',
    unitPrice: '20,000.00',
    isg: '123',
    commodityCode: 'b234',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'sms',
    location: '01af07b025',
    nmfc: '251234',
    description: 'heavy-duty aircraft landing gear assembly',
    manufacturer: 'landing gear co.',
  },
  {
    nomenclature: 'avionics module',
    nsn: '5456789012345',
    partNumber: 'avm789',
    cageCode: 'ghi56',
    unitOfIssue: 'EA',
    unitPrice: '15,000.00',
    isg: '123',
    commodityCode: 'c345',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'fdz',
    location: '01ag05b030',
    nmfc: '251345',
    description: 'advanced avionics control module',
    manufacturer: 'avionics inc.',
  },
  {
    nomenclature: 'hydraulic pump',
    nsn: '7567890123456',
    partNumber: 'hp567',
    cageCode: 'jkl78',
    unitOfIssue: 'EA',
    unitPrice: '10,000.00',
    isg: '123',
    commodityCode: 'd456',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'fhz',
    location: '01ah12b042',
    nmfc: '251456',
    description: 'high-pressure hydraulic pump unit',
    manufacturer: 'hydraulics corp.',
  },
  {
    nomenclature: 'aircraft fuselage',
    nsn: '5678301234567',
    partNumber: 'fus890',
    cageCode: 'mno89',
    unitOfIssue: 'EA',
    unitPrice: '70,000.00',
    isg: '123',
    commodityCode: 'e567',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'sms',
    location: '01ai03b058',
    nmfc: '251567',
    description: 'main structural body of the aircraft',
    manufacturer: 'fuselage co.',
  },
  {
    nomenclature: 'stabilizer control unit',
    nsn: '6789032345678',
    partNumber: 'scu345',
    cageCode: 'pqr90',
    unitOfIssue: 'EA',
    unitPrice: '28,000.00',
    isg: '123',
    commodityCode: 'f678',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'dds',
    location: '09ba09b015',
    nmfc: '251678',
    description: 'control unit for aircraft stabilizers',
    manufacturer: 'control systems inc.',
  },
  {
    nomenclature: 'radome assembly',
    nsn: '7890123456589',
    partNumber: 'rad456',
    cageCode: 'stu01',
    unitOfIssue: 'EA',
    unitPrice: '18,000.00',
    isg: '123',
    commodityCode: 'g789',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'sms',
    location: '09bb04b021',
    nmfc: '251789',
    description: 'protective cover for aircraft radar systems',
    manufacturer: 'radome corp.',
  },
  {
    nomenclature: 'airborne radar system',
    nsn: '8901234567890',
    partNumber: 'ars567',
    cageCode: 'uvw12',
    unitOfIssue: 'EA',
    unitPrice: '35,000.00',
    isg: '123',
    commodityCode: 'h890',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'fbz',
    location: '09bc05b035',
    nmfc: '251890',
    description: 'advanced radar system for aircraft surveillance',
    manufacturer: 'radar systems inc.',
  },
  {
    nomenclature: 'communications antenna',
    nsn: '9212345678901',
    partNumber: 'ca012',
    cageCode: 'xyz23',
    unitOfIssue: 'EA',
    unitPrice: '12,000.00',
    isg: '123',
    commodityCode: 'i901',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'fhz',
    location: '09bd11b047',
    nmfc: '251901',
    description: 'antenna system for aircraft communication systems',
    manufacturer: 'communication technologies inc.',
  },
  {
    nomenclature: 'cabin interior panel',
    nsn: '0123456789012',
    partNumber: 'cip234',
    cageCode: 'wxy34',
    unitOfIssue: 'EA',
    unitPrice: '20,000.00',
    isg: '123',
    commodityCode: 'j012',
    shelfLifeCode: '0',
    typeCargoCode: 'z',
    hazardousMaterialCode: 'n1',
    rid: 'sms',
    location: '09be08b053',
    nmfc: '251012',
    description: 'interior paneling for aircraft cabin compartments',
    manufacturer: 'interior panels ltd.'
},
{
    nomenclature: 'Missile Propellant Tank',
    nsn: '1354678901245',
    partNumber: 'mpt606',
    cageCode: 'uvw34',
    unitOfIssue: 'EA',
    unitPrice: '$40,000.00',
    isg: '250',
    commodityCode: 'p606',
    shelfLifeCode: '2',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h6',
    rid: 'rtz',
    location: '07di13f075',
    nmfc: '257606',
    description: 'tank for storing missile propellant',
    manufacturer: 'propellant storage inc.'
},
{
    nomenclature: 'Warhead Arming Device',
    nsn: '2465789012356',
    partNumber: 'wad707',
    cageCode: 'xyz45',
    unitOfIssue: 'EA',
    unitPrice: '$33,000.00',
    isg: '250',
    commodityCode: 'w707',
    shelfLifeCode: '2',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h7',
    rid: 'qaz',
    location: '08ej14g080',
    nmfc: '258707',
    description: 'device for arming the missile warhead',
    manufacturer: 'warhead tech ltd.'
},
{
    nomenclature: 'Blast Shield',
    nsn: '3576890123467',
    partNumber: 'bs808',
    cageCode: 'abc56',
    unitOfIssue: 'EA',
    unitPrice: '$27,000.00',
    isg: '250',
    commodityCode: 'b808',
    shelfLifeCode: '2',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h8',
    rid: 'wsx',
    location: '09fi15h085',
    nmfc: '259808',
    description: 'shield for protecting against blast effects',
    manufacturer: 'blast protect inc.'
},
{
    nomenclature: 'Siloe Elevator Mechanism',
    nsn: '4687901234578',
    partNumber: 'sem909',
    cageCode: 'def67',
    unitOfIssue: 'EA',
    unitPrice: '$50,000.00',
    isg: '300',
    commodityCode: 's909',
    shelfLifeCode: '3',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h9',
    rid: 'edc',
    location: '10gj16i090',
    nmfc: '260909',
    description: 'mechanism for raising and lowering the missile in the siloe',
    manufacturer: 'elevator systems inc.'
},
{
    nomenclature: 'Missile Cooling System',
    nsn: '5798012345689',
    partNumber: 'mcs1010',
    cageCode: 'ghi78',
    unitOfIssue: 'EA',
    unitPrice: '$22,500.00',
    isg: '300',
    commodityCode: 'm1010',
    shelfLifeCode: '3',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h10',
    rid: 'rfv',
    location: '11hk17j095',
    nmfc: '261010',
    description: 'system to maintain optimal temperature for missile components',
    manufacturer: 'cooling tech ltd.'
},
{
    nomenclature: 'Targeting System Interface',
    nsn: '6809123456790',
    partNumber: 'tsi1111',
    cageCode: 'jkl89',
    unitOfIssue: 'EA',
    unitPrice: '$35,000.00',
    isg: '300',
    commodityCode: 't1111',
    shelfLifeCode: '3',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h11',
    rid: 'tgb',
    location: '12il18k100',
    nmfc: '262111',
    description: 'interface for missile targeting systems',
    manufacturer: 'targeting solutions inc.'
},
{
    nomenclature: 'Fuel Valve Control Unit',
    nsn: '7910234567801',
    partNumber: 'fvcu1212',
    cageCode: 'mno90',
    unitOfIssue: 'EA',
    unitPrice: '$19,000.00',
    isg: '300',
    commodityCode: 'f1212',
    shelfLifeCode: '3',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h12',
    rid: 'yhn',
    location: '13jm19l105',
    nmfc: '263212',
    description: 'unit for controlling fuel valves in missile systems',
    manufacturer: 'valve control inc.'
},
{
    nomenclature: 'Emergency Shutdown System',
    nsn: '8021345678912',
    partNumber: 'ess1313',
    cageCode: 'pqr01',
    unitOfIssue: 'EA',
    unitPrice: '$48,000.00',
    isg: '350',
    commodityCode: 'e1313',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h13',
    rid: 'ujm',
    location: '14kn20m110',
    nmfc: '264313',
    description: 'system for rapid shutdown of missile operations in emergencies',
    manufacturer: 'safety systems ltd.'
},
{
    nomenclature: 'Guidance Module',
    nsn: '1264567890123',
    partNumber: 'gm2025',
    cageCode: 'pqr12',
    unitOfIssue: 'EA',
    unitPrice: '$55,000.00',
    isg: '350',
    commodityCode: 'g2025',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h14',
    rid: 'vbn',
    location: '15lm21n115',
    nmfc: '265425',
    description: 'module for guiding the missile to its target',
    manufacturer: 'guidance systems inc.'
},
{
    nomenclature: 'Launch Tube',
    nsn: '2345678901234',
    partNumber: 'lt3030',
    cageCode: 'stu23',
    unitOfIssue: 'EA',
    unitPrice: '$25,000.00',
    isg: '350',
    commodityCode: 'l3030',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h15',
    rid: 'cxz',
    location: '16no22p120',
    nmfc: '266530',
    description: 'tube for launching the missile from the launcher',
    manufacturer: 'launch systems ltd.'
},
{
    nomenclature: 'Thrust Vector Control System',
    nsn: '3456789012345',
    partNumber: 'tvcs4040',
    cageCode: 'vwx34',
    unitOfIssue: 'EA',
    unitPrice: '$38,000.00',
    isg: '350',
    commodityCode: 't4040',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h16',
    rid: 'bvc',
    location: '17op23q125',
    nmfc: '267640',
    description: 'system for controlling the missile\'s thrust direction',
    manufacturer: 'thrust control systems inc.'
},
{
    nomenclature: 'Missile Body',
    nsn: '4567890123456',
    partNumber: 'mb5050',
    cageCode: 'yza45',
    unitOfIssue: 'EA',
    unitPrice: '$42,000.00',
    isg: '350',
    commodityCode: 'm5050',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h17',
    rid: 'nmk',
    location: '18pq24r130',
    nmfc: '268750',
    description: 'main body structure of the missile',
    manufacturer: 'missile bodies inc.'
},
{
    nomenclature: 'Ignition System',
    nsn: '5678901234567',
    partNumber: 'is6060',
    cageCode: 'bcd56',
    unitOfIssue: 'EA',
    unitPrice: '$28,000.00',
    isg: '350',
    commodityCode: 'i6060',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h18',
    rid: 'lop',
    location: '19qr25s135',
    nmfc: '269860',
    description: 'system for igniting the missile\'s propulsion system',
    manufacturer: 'ignition tech inc.'
},
{
    nomenclature: 'Stabilization Fins',
    nsn: '6789012345678',
    partNumber: 'sf7070',
    cageCode: 'efg67',
    unitOfIssue: 'EA',
    unitPrice: '$15,000.00',
    isg: '350',
    commodityCode: 's7070',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h19',
    rid: 'zxc',
    location: '20rs26t140',
    nmfc: '270970',
    description: 'fins for stabilizing the missile during flight',
    manufacturer: 'stabilization systems ltd.'
},
{
    nomenclature: 'Warhead Payload',
    nsn: '7890123456789',
    partNumber: 'wp8080',
    cageCode: 'hij78',
    unitOfIssue: 'EA',
    unitPrice: '$65,000.00',
    isg: '350',
    commodityCode: 'w8080',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h20',
    rid: 'dfg',
    location: '21tu27v145',
    nmfc: '271080',
    description: 'explosive payload for the missile warhead',
    manufacturer: 'warhead payloads inc.'
},
{
    nomenclature: 'Communication Module',
    nsn: '8901234564890',
    partNumber: 'cm9090',
    cageCode: 'klm89',
    unitOfIssue: 'EA',
    unitPrice: '$30,000.00',
    isg: '350',
    commodityCode: 'c9090',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h21',
    rid: 'qwe',
    location: '22uv28w150',
    nmfc: '272190',
    description: 'module for communication between the missile and ground control',
    manufacturer: 'communication systems ltd.'
},
{
    nomenclature: 'Reentry Vehicle',
    nsn: '9012345678901',
    partNumber: 'rv1010',
    cageCode: 'nop90',
    unitOfIssue: 'EA',
    unitPrice: '$70,000.00',
    isg: '350',
    commodityCode: 'r1010',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h22',
    rid: 'mnb',
    location: '23wx29y155',
    nmfc: '273100',
    description: 'vehicle for reentering the atmosphere with the warhead',
    manufacturer: 'reentry systems inc.'
},
{
    nomenclature: 'Detonation Sensor',
    nsn: '4123456789012',
    partNumber: 'ds1212',
    cageCode: 'stu01',
    unitOfIssue: 'EA',
    unitPrice: '$20,000.00',
    isg: '350',
    commodityCode: 'd1212',
    shelfLifeCode: '4',
    typeCargoCode: 'm',
    hazardousMaterialCode: 'h23',
    rid: 'poi',
    location: '24xy30z160',
    nmfc: '274210',
    description: 'sensor for detecting the right moment for detonating the warhead',
    manufacturer: 'sensor technologies ltd.'
}
]
